### ISSUE TITLE
[BUG] ImportError: cannot import name 'AwqGEMMQuantLinear' from 'gptqmodel.nn_modules.qlinear.gemm_awq' in peft 0.19

### ISSUE THREAD

**Issue by akowalsk** [huggingface/peft#3264]
### System Info

- `transformers` version: 5.8.1
- Platform: Linux-5.15.0-173-generic-x86_64-with-glibc2.35
- Python version: 3.12.13
- Huggingface_hub version: 1.14.0
- Safetensors version: 0.7.0
- Accelerate version: 1.13.0
- Accelerate config:    not found
- DeepSpeed version: 0.19.0
- PyTorch version (accelerator?): 2.11.0+cu130 (CUDA)
- Using distributed or parallel set-up in script?: No
- Using GPU in script?: yes
- GPU type: NVIDIA GeForce RTX 3090
GPTQModel                                7.0.0
peft                                     0.19.1
trl                                      1.5.0

### Who can help?

@benjaminbossan @githubnemo

### Reproduction

I get the following error when trying to train an adapter on peft 0.19.0 or 0.19.1 (works on 0.18.1):

```
GPT-QModel   : 7.0.0+1cd694c
Transformers : 5.8.1
Torch        : 2.11.0+cu130
Triton       : 3.6.0
[rank0]: Traceback (most recent call last):
[rank0]:   File "/opt/ml/models/train_lora_accelerate.py", line 356, in <module>
[rank0]:     trainer = SFTTrainer(
[rank0]:               ^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/trl/trainer/sft_trainer.py", line 1065, in __init__
[rank0]:     model = get_peft_model(model, peft_config)
[rank0]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py", line 122, in get_peft_model
[rank0]:     return MODEL_TYPE_TO_PEFT_MODEL_MAPPING[peft_config.task_type](
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/peft/peft_model.py", line 1955, in __init__
[rank0]:     super().__init__(model, peft_config, adapter_name, **kwargs)
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/peft/peft_model.py", line 129, in __init__
[rank0]:     self.base_model = cls(model, {adapter_name: peft_config}, adapter_name)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py", line 315, in __init__
[rank0]:     self.inject_adapter(self.model, adapter_name, low_cpu_mem_usage=low_cpu_mem_usage, state_dict=state_dict)
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py", line 913, in inject_adapter
[rank0]:     self._create_and_replace(
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/model.py", line 269, in _create_and_replace
[rank0]:     new_module = self._create_new_module(lora_config, adapter_name, target, device_map=device_map, **kwargs)
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/model.py", line 418, in _create_new_module
[rank0]:     new_module = dispatcher(target, adapter_name, config=lora_config, **kwargs)
[rank0]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/local/lib/python3.12/dist-packages/peft/tuners/lora/awq.py", line 98, in dispatch_awq
[rank0]:     from gptqmodel.nn_modules.qlinear.gemm_awq import AwqGEMMQuantLinear
[rank0]: ImportError: cannot import name 'AwqGEMMQuantLinear' from 'gptqmodel.nn_modules.qlinear.gemm_awq' (/usr/local/lib/python3.12/dist-packages/gptqmodel/nn_modules/qlinear/gemm_awq.py). Did you mean: 'AwqGEMMLinear'?
```

My Lora/SFTTrainer config is:

```
peft_config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=target_modules,
    ensure_weight_tying=True,
    trainable_token_indices={"embed_tokens": new_token_indices},
    lora_dropout=0.15,
    bias="none",
    task_type="CAUSAL_LM",
)
training_args = SFTConfig(
    output_dir=output_dir,
    num_train_epochs=num_epochs,
    per_device_train_batch_size=per_device_batch_size,
    per_device_eval_batch_size=per_device_batch_size,
    learning_rate=learning_rate,
    lr_scheduler_type="cosine",
    warmup_ratio=0.2,
    weight_decay=0.05,
    eval_strategy="steps",
    save_strategy="steps",
    save_steps=int(len(train_dataset) / 2),
    eval_steps=int(len(train_dataset) / 2),
    logging_steps=10,
    metric_for_best_model="eval_loss",
    load_best_model_at_end=True,
    max_grad_norm=1,
    # report_to="tensorboard",
    ddp_find_unused_parameters=False,
    dataset_kwargs={"skip_prepare_dataset": True},
    remove_unused_columns=False,
    optim="adamw_torch",
    completion_only_loss=True,
    max_length=max_seq_length,
    ## memory stuff
    use_liger_kernel=False,
    # gradient_checkpointing=True,
    # activation_offloading=True,  ## not compatible with deep speed and doesn't really help without it
)
trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    peft_config=peft_config,
    processing_class=processor,
)
```
I am using deepspeed zero 2 with the following config:
```
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: none
  offload_param_device: none
  zero3_init_flag: false
  zero3_save_16bit_model: true
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: "no"
machine_rank: 0
main_training_function: main
mixed_precision: "bf16"
num_machines: 1
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```
but I doubt that is related.

I also believe that I had previously trained just fine on 0.19.0 before GPTQModel released 7.0, but I cannot be certain on that.

My larger concern is that I'm not using an AWQ model (I'm using the vanilla Qwen3.5-4B model), but it's erroring because of this anyway.

### Expected behavior

I would expect to be able to load and train a PEFT model in regular FP16 mode regardless of my GPTQModel setup or library incompatibilities.

**Comment by BenjaminBossan** [comment]
Thanks for reporting. The issue should be fixed in #3190. If that's an option for you, install PEFT from main and try if it helps.

> My larger concern is that I'm not using an AWQ model (I'm using the vanilla Qwen3.5-4B model), but it's erroring because of this anyway.

Even if you're not using it, if gptqmodel is installed, we need to check if it's being used. You can uninstall gptqmodel in your env if you want to prevent that.

**Comment by akowalsk** [comment]
Install from main fixed it.  Thanks!
