### ISSUE TITLE
AttributeError: 'GPTNeoXForCausalLM' object has no attribute 'lm_head'

### ISSUE THREAD

**Issue by banank1989** [huggingface/peft#521]
I am trying to fine-tune **OpenAssistant/oasst-sft-4-pythia-12b-epoch-3.5** and I am getting this error 
```
AttributeError: 'GPTNeoXForCausalLM' object has no attribute 'lm_head'
```

Same code is working with model : **facebook/opt-6.7b**
Referring this notebook for code : https://colab.research.google.com/drive/1jCkpikz0J2o20FBQmYmAGdiKmJGOMo-o?usp=sharing#scrollTo=cg3fiQOvmI3Q
